### ISSUE TITLE
Carbon X: Elements

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#47]
## Packages

- [ ] Grid
  - [x] Get final decision artifacts for grid implementation
  - [ ] Initial grid implementation and browser testing
  - [ ] Comment period
  - [ ] Second (final) implementation for Carbon X (bug fixes welcome)
  - [ ] Add JavaScript-specific bindings
  - [ ] Add developer documentation (README or site?)
- [ ] Colors
  - [x] Get final palette to implement for X
  - [x] Get final token values
  - [ ] Make decision on interaction color strategy
  - [ ] Verify support in SCSS
  - [ ] Verify support in JS
  - [ ] Developer documentation (README or site?)
- [ ] Icons
  - [ ] Decide on migration strategy
  - [ ] Create migration documentation
  - [ ] Verify JavaScript bindings
  - [ ] Verify React.js bindings
  - [ ] Create bindings for Angular
  - [ ] Create bindings for Vue
  - [ ] Developer documentation for each package (README or site?)
- [ ] Type
  - [x] Settle on token values and names
  - [x] Decide strategy on responsive styles
  - [ ] Provide SCSS and JS bindings for type styles
  - [ ] Decide strategy on vertical spacing
- [ ] All
  - [ ] Should we support exporting to sketch libraries?
  - [ ] Public 1.0 Release Candidates for Technical Preview, tag as next
  - [ ] Publish 1.0 versions for Carbon X, tag as latest
- [ ] Education & Activation, Communication
  - [ ] Provide messaging around Technical Preview of code
  - [ ] Align with Elements course (?) on deliverables of sketch assets
  - [ ] Development and design documentation or guidance (README? Site?)
  - [ ] Make sure original design authors get credit in corresponding packages
  - [ ] Medium post for release
- [ ] Motion - content is for motion in UI which is complete and can be ported over directly
